# Generated by Django 4.2.4 on 2023-08-26 17:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('save_the_date', '0006_alter_question_pub_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='savethedate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='savethedate',
            name='time',
        ),
        migrations.AddField(
            model_name='savethedate',
            name='event_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='event_date'),
            preserve_default=False,
        ),
    ]
